/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Testimonial {
    id: bigint;
    quote: string;
    author: string;
    rating: bigint;
}
export interface AnalyticsSummary {
    pendingApprovals: bigint;
    totalProperties: bigint;
    totalEnquiries: bigint;
    totalUsers: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Enquiry {
    id: bigint;
    senderPhone: string;
    propertyId: bigint;
    message: string;
    timestamp: bigint;
    senderName: string;
    senderEmail: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface Property {
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    isLuxury: boolean;
    owner: Principal;
    carpetArea: bigint;
    bhkType: BhkType;
    builtUpArea: bigint;
    description: string;
    amenities: Array<Amenity>;
    isUnderConstruction: boolean;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Amenity {
    gym = "gym",
    swimmingPool = "swimmingPool",
    garden = "garden",
    security = "security",
    playground = "playground",
    parking = "parking"
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum BhkType {
    bhk1 = "bhk1",
    bhk2 = "bhk2",
    bhk3 = "bhk3",
    bhk4 = "bhk4",
    bhk5plus = "bhk5plus"
}
export enum ListingStatus {
    active = "active",
    pending = "pending",
    rent = "rent",
    sold = "sold"
}
export enum PropertyType {
    commercial = "commercial",
    villa = "villa",
    plot = "plot",
    apartment = "apartment",
    rowHouse = "rowHouse"
}
export enum Role {
    admin = "admin",
    user = "user"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAmenities(propertyId: bigint, amenities: Array<Amenity>): Promise<void>;
    addToWishlist(propertyId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRole(user: Principal, role: Role): Promise<void>;
    createEnquiry(enquiry: {
        senderPhone: string;
        propertyId: bigint;
        message: string;
        timestamp: bigint;
        senderName: string;
        senderEmail: string;
    }): Promise<bigint>;
    createProperty(property: {
        status: ListingStatus;
        title: string;
        propertyType: PropertyType;
        isLuxury: boolean;
        carpetArea: bigint;
        bhkType: BhkType;
        builtUpArea: bigint;
        description: string;
        isUnderConstruction: boolean;
        isFeatured: boolean;
        price: bigint;
        location: string;
    }): Promise<bigint>;
    createTestimonial(testimonial: {
        quote: string;
        author: string;
        rating: bigint;
    }): Promise<bigint>;
    deleteProperty(propertyId: bigint): Promise<void>;
    getAllUsers(): Promise<Array<{
        principal: Principal;
        name: string;
        role: Role;
        email: string;
        phone: string;
    }>>;
    getAnalyticsSummary(): Promise<AnalyticsSummary>;
    getCallerUserProfile(): Promise<{
        name: string;
        email: string;
        phone: string;
    }>;
    getCallerUserRole(): Promise<UserRole>;
    getEnquiries(): Promise<Array<Enquiry>>;
    getEnquiriesForProperty(propertyId: bigint): Promise<Array<Enquiry>>;
    getFeaturedProperties(): Promise<Array<Property>>;
    getForRentProperties(): Promise<Array<Property>>;
    getMyProperties(): Promise<Array<Property>>;
    getProperties(): Promise<Array<Property>>;
    getProperty(id: bigint): Promise<Property>;
    getSortedPropertiesByLocation(): Promise<Array<Property>>;
    getSortedPropertiesByPrice(_ascending: boolean): Promise<Array<Property>>;
    getTestimonials(): Promise<Array<Testimonial>>;
    getUserProfile(target: Principal): Promise<{
        name: string;
        email: string;
        phone: string;
    }>;
    getWishlist(): Promise<Array<bigint>>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    removeFromWishlist(propertyId: bigint): Promise<void>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: {
        name: string;
        email: string;
        phone: string;
    }): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    setPropertyFeatured(propertyId: bigint, isFeatured: boolean): Promise<void>;
    setPropertyStatus(propertyId: bigint, status: ListingStatus): Promise<void>;
    updateProperty(propertyId: bigint, update: {
        status: ListingStatus;
        title: string;
        propertyType: PropertyType;
        isLuxury: boolean;
        carpetArea: bigint;
        bhkType: BhkType;
        builtUpArea: bigint;
        description: string;
        isUnderConstruction: boolean;
        price: bigint;
        location: string;
    }): Promise<void>;
}
import type { Amenity as _Amenity, ApprovalStatus as _ApprovalStatus, BhkType as _BhkType, ExternalBlob as _ExternalBlob, ListingStatus as _ListingStatus, Property as _Property, PropertyType as _PropertyType, Role as _Role, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAmenities(arg0: bigint, arg1: Array<Amenity>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAmenities(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAmenities(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async addToWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToWishlist(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRole(arg0: Principal, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRole(arg0, to_candid_Role_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRole(arg0, to_candid_Role_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEnquiry(arg0: {
        senderPhone: string;
        propertyId: bigint;
        message: string;
        timestamp: bigint;
        senderName: string;
        senderEmail: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEnquiry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEnquiry(arg0);
            return result;
        }
    }
    async createProperty(arg0: {
        status: ListingStatus;
        title: string;
        propertyType: PropertyType;
        isLuxury: boolean;
        carpetArea: bigint;
        bhkType: BhkType;
        builtUpArea: bigint;
        description: string;
        isUnderConstruction: boolean;
        isFeatured: boolean;
        price: bigint;
        location: string;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProperty(to_candid_record_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProperty(to_candid_record_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createTestimonial(arg0: {
        quote: string;
        author: string;
        rating: bigint;
    }): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestimonial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestimonial(arg0);
            return result;
        }
    }
    async deleteProperty(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProperty(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<{
        principal: Principal;
        name: string;
        role: Role;
        email: string;
        phone: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalyticsSummary(): Promise<AnalyticsSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalyticsSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalyticsSummary();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<{
        name: string;
        email: string;
        phone: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEnquiries(): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiries();
            return result;
        }
    }
    async getEnquiriesForProperty(arg0: bigint): Promise<Array<Enquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEnquiriesForProperty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEnquiriesForProperty(arg0);
            return result;
        }
    }
    async getFeaturedProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedProperties();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedProperties();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForRentProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getForRentProperties();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForRentProperties();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProperties();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProperties();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperties(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperties();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperties();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProperty(arg0: bigint): Promise<Property> {
        if (this.processError) {
            try {
                const result = await this.actor.getProperty(arg0);
                return from_candid_Property_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProperty(arg0);
            return from_candid_Property_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedPropertiesByLocation(): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedPropertiesByLocation();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedPropertiesByLocation();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSortedPropertiesByPrice(arg0: boolean): Promise<Array<Property>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSortedPropertiesByPrice(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSortedPropertiesByPrice(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestimonials(): Promise<Array<Testimonial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestimonials();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestimonials();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<{
        name: string;
        email: string;
        phone: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return result;
        }
    }
    async getWishlist(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWishlist();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromWishlist(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromWishlist(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: {
        name: string;
        email: string;
        phone: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n47(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n47(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setPropertyFeatured(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPropertyFeatured(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPropertyFeatured(arg0, arg1);
            return result;
        }
    }
    async setPropertyStatus(arg0: bigint, arg1: ListingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPropertyStatus(arg0, to_candid_ListingStatus_n16(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPropertyStatus(arg0, to_candid_ListingStatus_n16(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProperty(arg0: bigint, arg1: {
        status: ListingStatus;
        title: string;
        propertyType: PropertyType;
        isLuxury: boolean;
        carpetArea: bigint;
        bhkType: BhkType;
        builtUpArea: bigint;
        description: string;
        isUnderConstruction: boolean;
        price: bigint;
        location: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProperty(arg0, to_candid_record_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProperty(arg0, to_candid_record_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Amenity_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Amenity): Amenity {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_BhkType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BhkType): BhkType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ListingStatus_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingStatus): ListingStatus {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PropertyType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PropertyType): PropertyType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Property_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Property): Promise<Property> {
    return await from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    role: _Role;
    email: string;
    phone: string;
}): {
    principal: Principal;
    name: string;
    role: Role;
    email: string;
    phone: string;
} {
    return {
        principal: value.principal,
        name: value.name,
        role: from_candid_Role_n24(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
async function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    isLuxury: boolean;
    owner: Principal;
    carpetArea: bigint;
    bhkType: _BhkType;
    builtUpArea: bigint;
    description: string;
    amenities: Array<_Amenity>;
    isUnderConstruction: boolean;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: bigint;
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    isLuxury: boolean;
    owner: Principal;
    carpetArea: bigint;
    bhkType: BhkType;
    builtUpArea: bigint;
    description: string;
    amenities: Array<Amenity>;
    isUnderConstruction: boolean;
    isFeatured: boolean;
    price: bigint;
    location: string;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_ListingStatus_n31(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: from_candid_PropertyType_n33(_uploadFile, _downloadFile, value.propertyType),
        isLuxury: value.isLuxury,
        owner: value.owner,
        carpetArea: value.carpetArea,
        bhkType: from_candid_BhkType_n35(_uploadFile, _downloadFile, value.bhkType),
        builtUpArea: value.builtUpArea,
        description: value.description,
        amenities: from_candid_vec_n37(_uploadFile, _downloadFile, value.amenities),
        isUnderConstruction: value.isUnderConstruction,
        isFeatured: value.isFeatured,
        price: value.price,
        location: value.location,
        images: await from_candid_vec_n40(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n45(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    pending: null;
} | {
    rent: null;
} | {
    sold: null;
}): ListingStatus {
    return "active" in value ? ListingStatus.active : "pending" in value ? ListingStatus.pending : "rent" in value ? ListingStatus.rent : "sold" in value ? ListingStatus.sold : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    commercial: null;
} | {
    villa: null;
} | {
    plot: null;
} | {
    apartment: null;
} | {
    rowHouse: null;
}): PropertyType {
    return "commercial" in value ? PropertyType.commercial : "villa" in value ? PropertyType.villa : "plot" in value ? PropertyType.plot : "apartment" in value ? PropertyType.apartment : "rowHouse" in value ? PropertyType.rowHouse : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bhk1: null;
} | {
    bhk2: null;
} | {
    bhk3: null;
} | {
    bhk4: null;
} | {
    bhk5plus: null;
}): BhkType {
    return "bhk1" in value ? BhkType.bhk1 : "bhk2" in value ? BhkType.bhk2 : "bhk3" in value ? BhkType.bhk3 : "bhk4" in value ? BhkType.bhk4 : "bhk5plus" in value ? BhkType.bhk5plus : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gym: null;
} | {
    swimmingPool: null;
} | {
    garden: null;
} | {
    security: null;
} | {
    playground: null;
} | {
    parking: null;
}): Amenity {
    return "gym" in value ? Amenity.gym : "swimmingPool" in value ? Amenity.swimmingPool : "garden" in value ? Amenity.garden : "security" in value ? Amenity.security : "playground" in value ? Amenity.playground : "parking" in value ? Amenity.parking : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    principal: Principal;
    name: string;
    role: _Role;
    email: string;
    phone: string;
}>): Array<{
    principal: Principal;
    name: string;
    role: Role;
    email: string;
    phone: string;
}> {
    return value.map((x)=>from_candid_record_n23(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Property>): Promise<Array<Property>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Property_n29(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Amenity>): Array<Amenity> {
    return value.map((x)=>from_candid_Amenity_n38(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n41(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n43(_uploadFile, _downloadFile, x));
}
function to_candid_Amenity_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Amenity): _Amenity {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_BhkType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BhkType): _BhkType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ListingStatus_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): _ListingStatus {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_PropertyType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): _PropertyType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    isLuxury: boolean;
    carpetArea: bigint;
    bhkType: BhkType;
    builtUpArea: bigint;
    description: string;
    isUnderConstruction: boolean;
    isFeatured: boolean;
    price: bigint;
    location: string;
}): {
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    isLuxury: boolean;
    carpetArea: bigint;
    bhkType: _BhkType;
    builtUpArea: bigint;
    description: string;
    isUnderConstruction: boolean;
    isFeatured: boolean;
    price: bigint;
    location: string;
} {
    return {
        status: to_candid_ListingStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: to_candid_PropertyType_n18(_uploadFile, _downloadFile, value.propertyType),
        isLuxury: value.isLuxury,
        carpetArea: value.carpetArea,
        bhkType: to_candid_BhkType_n20(_uploadFile, _downloadFile, value.bhkType),
        builtUpArea: value.builtUpArea,
        description: value.description,
        isUnderConstruction: value.isUnderConstruction,
        isFeatured: value.isFeatured,
        price: value.price,
        location: value.location
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: ListingStatus;
    title: string;
    propertyType: PropertyType;
    isLuxury: boolean;
    carpetArea: bigint;
    bhkType: BhkType;
    builtUpArea: bigint;
    description: string;
    isUnderConstruction: boolean;
    price: bigint;
    location: string;
}): {
    status: _ListingStatus;
    title: string;
    propertyType: _PropertyType;
    isLuxury: boolean;
    carpetArea: bigint;
    bhkType: _BhkType;
    builtUpArea: bigint;
    description: string;
    isUnderConstruction: boolean;
    price: bigint;
    location: string;
} {
    return {
        status: to_candid_ListingStatus_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        propertyType: to_candid_PropertyType_n18(_uploadFile, _downloadFile, value.propertyType),
        isLuxury: value.isLuxury,
        carpetArea: value.carpetArea,
        bhkType: to_candid_BhkType_n20(_uploadFile, _downloadFile, value.bhkType),
        builtUpArea: value.builtUpArea,
        description: value.description,
        isUnderConstruction: value.isUnderConstruction,
        price: value.price,
        location: value.location
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Amenity): {
    gym: null;
} | {
    swimmingPool: null;
} | {
    garden: null;
} | {
    security: null;
} | {
    playground: null;
} | {
    parking: null;
} {
    return value == Amenity.gym ? {
        gym: null
    } : value == Amenity.swimmingPool ? {
        swimmingPool: null
    } : value == Amenity.garden ? {
        garden: null
    } : value == Amenity.security ? {
        security: null
    } : value == Amenity.playground ? {
        playground: null
    } : value == Amenity.parking ? {
        parking: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    user: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingStatus): {
    active: null;
} | {
    pending: null;
} | {
    rent: null;
} | {
    sold: null;
} {
    return value == ListingStatus.active ? {
        active: null
    } : value == ListingStatus.pending ? {
        pending: null
    } : value == ListingStatus.rent ? {
        rent: null
    } : value == ListingStatus.sold ? {
        sold: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PropertyType): {
    commercial: null;
} | {
    villa: null;
} | {
    plot: null;
} | {
    apartment: null;
} | {
    rowHouse: null;
} {
    return value == PropertyType.commercial ? {
        commercial: null
    } : value == PropertyType.villa ? {
        villa: null
    } : value == PropertyType.plot ? {
        plot: null
    } : value == PropertyType.apartment ? {
        apartment: null
    } : value == PropertyType.rowHouse ? {
        rowHouse: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BhkType): {
    bhk1: null;
} | {
    bhk2: null;
} | {
    bhk3: null;
} | {
    bhk4: null;
} | {
    bhk5plus: null;
} {
    return value == BhkType.bhk1 ? {
        bhk1: null
    } : value == BhkType.bhk2 ? {
        bhk2: null
    } : value == BhkType.bhk3 ? {
        bhk3: null
    } : value == BhkType.bhk4 ? {
        bhk4: null
    } : value == BhkType.bhk5plus ? {
        bhk5plus: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Amenity>): Array<_Amenity> {
    return value.map((x)=>to_candid_Amenity_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
