/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Amenity = IDL.Variant({
  'gym' : IDL.Null,
  'swimmingPool' : IDL.Null,
  'garden' : IDL.Null,
  'security' : IDL.Null,
  'playground' : IDL.Null,
  'parking' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const ListingStatus = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'rent' : IDL.Null,
  'sold' : IDL.Null,
});
export const PropertyType = IDL.Variant({
  'commercial' : IDL.Null,
  'villa' : IDL.Null,
  'plot' : IDL.Null,
  'apartment' : IDL.Null,
  'rowHouse' : IDL.Null,
});
export const BhkType = IDL.Variant({
  'bhk1' : IDL.Null,
  'bhk2' : IDL.Null,
  'bhk3' : IDL.Null,
  'bhk4' : IDL.Null,
  'bhk5plus' : IDL.Null,
});
export const AnalyticsSummary = IDL.Record({
  'pendingApprovals' : IDL.Nat,
  'totalProperties' : IDL.Nat,
  'totalEnquiries' : IDL.Nat,
  'totalUsers' : IDL.Nat,
});
export const Enquiry = IDL.Record({
  'id' : IDL.Nat,
  'senderPhone' : IDL.Text,
  'propertyId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'status' : ListingStatus,
  'title' : IDL.Text,
  'propertyType' : PropertyType,
  'isLuxury' : IDL.Bool,
  'owner' : IDL.Principal,
  'carpetArea' : IDL.Nat,
  'bhkType' : BhkType,
  'builtUpArea' : IDL.Nat,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(Amenity),
  'isUnderConstruction' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'price' : IDL.Nat,
  'location' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'quote' : IDL.Text,
  'author' : IDL.Text,
  'rating' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAmenities' : IDL.Func([IDL.Nat, IDL.Vec(Amenity)], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignRole' : IDL.Func([IDL.Principal, Role], [], []),
  'createEnquiry' : IDL.Func(
      [
        IDL.Record({
          'senderPhone' : IDL.Text,
          'propertyId' : IDL.Nat,
          'message' : IDL.Text,
          'timestamp' : IDL.Int,
          'senderName' : IDL.Text,
          'senderEmail' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'createProperty' : IDL.Func(
      [
        IDL.Record({
          'status' : ListingStatus,
          'title' : IDL.Text,
          'propertyType' : PropertyType,
          'isLuxury' : IDL.Bool,
          'carpetArea' : IDL.Nat,
          'bhkType' : BhkType,
          'builtUpArea' : IDL.Nat,
          'description' : IDL.Text,
          'isUnderConstruction' : IDL.Bool,
          'isFeatured' : IDL.Bool,
          'price' : IDL.Nat,
          'location' : IDL.Text,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'createTestimonial' : IDL.Func(
      [
        IDL.Record({
          'quote' : IDL.Text,
          'author' : IDL.Text,
          'rating' : IDL.Nat,
        }),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({
            'principal' : IDL.Principal,
            'name' : IDL.Text,
            'role' : Role,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [
        IDL.Record({
          'name' : IDL.Text,
          'email' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getEnquiriesForProperty' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Enquiry)],
      ['query'],
    ),
  'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getForRentProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getMyProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
  'getSortedPropertiesByLocation' : IDL.Func(
      [],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getSortedPropertiesByPrice' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(Property)],
      ['query'],
    ),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Record({
          'name' : IDL.Text,
          'email' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'email' : IDL.Text,
          'phone' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setPropertyFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setPropertyStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
  'updateProperty' : IDL.Func(
      [
        IDL.Nat,
        IDL.Record({
          'status' : ListingStatus,
          'title' : IDL.Text,
          'propertyType' : PropertyType,
          'isLuxury' : IDL.Bool,
          'carpetArea' : IDL.Nat,
          'bhkType' : BhkType,
          'builtUpArea' : IDL.Nat,
          'description' : IDL.Text,
          'isUnderConstruction' : IDL.Bool,
          'price' : IDL.Nat,
          'location' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Amenity = IDL.Variant({
    'gym' : IDL.Null,
    'swimmingPool' : IDL.Null,
    'garden' : IDL.Null,
    'security' : IDL.Null,
    'playground' : IDL.Null,
    'parking' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const ListingStatus = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'rent' : IDL.Null,
    'sold' : IDL.Null,
  });
  const PropertyType = IDL.Variant({
    'commercial' : IDL.Null,
    'villa' : IDL.Null,
    'plot' : IDL.Null,
    'apartment' : IDL.Null,
    'rowHouse' : IDL.Null,
  });
  const BhkType = IDL.Variant({
    'bhk1' : IDL.Null,
    'bhk2' : IDL.Null,
    'bhk3' : IDL.Null,
    'bhk4' : IDL.Null,
    'bhk5plus' : IDL.Null,
  });
  const AnalyticsSummary = IDL.Record({
    'pendingApprovals' : IDL.Nat,
    'totalProperties' : IDL.Nat,
    'totalEnquiries' : IDL.Nat,
    'totalUsers' : IDL.Nat,
  });
  const Enquiry = IDL.Record({
    'id' : IDL.Nat,
    'senderPhone' : IDL.Text,
    'propertyId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'status' : ListingStatus,
    'title' : IDL.Text,
    'propertyType' : PropertyType,
    'isLuxury' : IDL.Bool,
    'owner' : IDL.Principal,
    'carpetArea' : IDL.Nat,
    'bhkType' : BhkType,
    'builtUpArea' : IDL.Nat,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(Amenity),
    'isUnderConstruction' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'price' : IDL.Nat,
    'location' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'quote' : IDL.Text,
    'author' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAmenities' : IDL.Func([IDL.Nat, IDL.Vec(Amenity)], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignRole' : IDL.Func([IDL.Principal, Role], [], []),
    'createEnquiry' : IDL.Func(
        [
          IDL.Record({
            'senderPhone' : IDL.Text,
            'propertyId' : IDL.Nat,
            'message' : IDL.Text,
            'timestamp' : IDL.Int,
            'senderName' : IDL.Text,
            'senderEmail' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'createProperty' : IDL.Func(
        [
          IDL.Record({
            'status' : ListingStatus,
            'title' : IDL.Text,
            'propertyType' : PropertyType,
            'isLuxury' : IDL.Bool,
            'carpetArea' : IDL.Nat,
            'bhkType' : BhkType,
            'builtUpArea' : IDL.Nat,
            'description' : IDL.Text,
            'isUnderConstruction' : IDL.Bool,
            'isFeatured' : IDL.Bool,
            'price' : IDL.Nat,
            'location' : IDL.Text,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'createTestimonial' : IDL.Func(
        [
          IDL.Record({
            'quote' : IDL.Text,
            'author' : IDL.Text,
            'rating' : IDL.Nat,
          }),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({
              'principal' : IDL.Principal,
              'name' : IDL.Text,
              'role' : Role,
              'email' : IDL.Text,
              'phone' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getAnalyticsSummary' : IDL.Func([], [AnalyticsSummary], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getEnquiriesForProperty' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Enquiry)],
        ['query'],
      ),
    'getFeaturedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getForRentProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getMyProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([IDL.Nat], [Property], ['query']),
    'getSortedPropertiesByLocation' : IDL.Func(
        [],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getSortedPropertiesByPrice' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Property)],
        ['query'],
      ),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'email' : IDL.Text,
            'phone' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setPropertyFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setPropertyStatus' : IDL.Func([IDL.Nat, ListingStatus], [], []),
    'updateProperty' : IDL.Func(
        [
          IDL.Nat,
          IDL.Record({
            'status' : ListingStatus,
            'title' : IDL.Text,
            'propertyType' : PropertyType,
            'isLuxury' : IDL.Bool,
            'carpetArea' : IDL.Nat,
            'bhkType' : BhkType,
            'builtUpArea' : IDL.Nat,
            'description' : IDL.Text,
            'isUnderConstruction' : IDL.Bool,
            'price' : IDL.Nat,
            'location' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };