/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Amenity = { 'gym' : null } |
  { 'swimmingPool' : null } |
  { 'garden' : null } |
  { 'security' : null } |
  { 'playground' : null } |
  { 'parking' : null };
export interface AnalyticsSummary {
  'pendingApprovals' : bigint,
  'totalProperties' : bigint,
  'totalEnquiries' : bigint,
  'totalUsers' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type BhkType = { 'bhk1' : null } |
  { 'bhk2' : null } |
  { 'bhk3' : null } |
  { 'bhk4' : null } |
  { 'bhk5plus' : null };
export interface Enquiry {
  'id' : bigint,
  'senderPhone' : string,
  'propertyId' : bigint,
  'message' : string,
  'timestamp' : bigint,
  'senderName' : string,
  'senderEmail' : string,
}
export type ExternalBlob = Uint8Array;
export type ListingStatus = { 'active' : null } |
  { 'pending' : null } |
  { 'rent' : null } |
  { 'sold' : null };
export interface Property {
  'id' : bigint,
  'status' : ListingStatus,
  'title' : string,
  'propertyType' : PropertyType,
  'isLuxury' : boolean,
  'owner' : Principal,
  'carpetArea' : bigint,
  'bhkType' : BhkType,
  'builtUpArea' : bigint,
  'description' : string,
  'amenities' : Array<Amenity>,
  'isUnderConstruction' : boolean,
  'isFeatured' : boolean,
  'price' : bigint,
  'location' : string,
  'images' : Array<ExternalBlob>,
}
export type PropertyType = { 'commercial' : null } |
  { 'villa' : null } |
  { 'plot' : null } |
  { 'apartment' : null } |
  { 'rowHouse' : null };
export type Role = { 'admin' : null } |
  { 'user' : null };
export interface Testimonial {
  'id' : bigint,
  'quote' : string,
  'author' : string,
  'rating' : bigint,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAmenities' : ActorMethod<[bigint, Array<Amenity>], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignRole' : ActorMethod<[Principal, Role], undefined>,
  'createEnquiry' : ActorMethod<
    [
      {
        'senderPhone' : string,
        'propertyId' : bigint,
        'message' : string,
        'timestamp' : bigint,
        'senderName' : string,
        'senderEmail' : string,
      },
    ],
    bigint
  >,
  'createProperty' : ActorMethod<
    [
      {
        'status' : ListingStatus,
        'title' : string,
        'propertyType' : PropertyType,
        'isLuxury' : boolean,
        'carpetArea' : bigint,
        'bhkType' : BhkType,
        'builtUpArea' : bigint,
        'description' : string,
        'isUnderConstruction' : boolean,
        'isFeatured' : boolean,
        'price' : bigint,
        'location' : string,
      },
    ],
    bigint
  >,
  'createTestimonial' : ActorMethod<
    [{ 'quote' : string, 'author' : string, 'rating' : bigint }],
    bigint
  >,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'getAllUsers' : ActorMethod<
    [],
    Array<
      {
        'principal' : Principal,
        'name' : string,
        'role' : Role,
        'email' : string,
        'phone' : string,
      }
    >
  >,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getCallerUserProfile' : ActorMethod<
    [],
    { 'name' : string, 'email' : string, 'phone' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getEnquiriesForProperty' : ActorMethod<[bigint], Array<Enquiry>>,
  'getFeaturedProperties' : ActorMethod<[], Array<Property>>,
  'getForRentProperties' : ActorMethod<[], Array<Property>>,
  'getMyProperties' : ActorMethod<[], Array<Property>>,
  'getProperties' : ActorMethod<[], Array<Property>>,
  'getProperty' : ActorMethod<[bigint], Property>,
  'getSortedPropertiesByLocation' : ActorMethod<[], Array<Property>>,
  'getSortedPropertiesByPrice' : ActorMethod<[boolean], Array<Property>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getUserProfile' : ActorMethod<
    [Principal],
    { 'name' : string, 'email' : string, 'phone' : string }
  >,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [{ 'name' : string, 'email' : string, 'phone' : string }],
    undefined
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setPropertyFeatured' : ActorMethod<[bigint, boolean], undefined>,
  'setPropertyStatus' : ActorMethod<[bigint, ListingStatus], undefined>,
  'updateProperty' : ActorMethod<
    [
      bigint,
      {
        'status' : ListingStatus,
        'title' : string,
        'propertyType' : PropertyType,
        'isLuxury' : boolean,
        'carpetArea' : bigint,
        'bhkType' : BhkType,
        'builtUpArea' : bigint,
        'description' : string,
        'isUnderConstruction' : boolean,
        'price' : bigint,
        'location' : string,
      },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];